### ISSUE TITLE
imcomplete import

### ISSUE THREAD

**Issue by ghost** [gfwilliams/svgtoeagle#12]
Hi,
I made an SVG in Inkscape and prepared the image as described in the "How to use" and youtube video (Ungroup, Object to path, break apart). 
Unfortunately I have a few issues here.
The svg looks like this:
![image](https://user-images.githubusercontent.com/31340618/57476833-b8595080-7297-11e9-8463-1755364018ec.png)
On the svgtoeagle page, it looks like this (mm marks missing, bottom inch part missing, DNA parts missing):
![image](https://user-images.githubusercontent.com/31340618/57476895-df178700-7297-11e9-99b3-8e1fed0bdbb0.png)
When executing the downloaded eagle script, it looks like this (cm scale missing and all from above missing):
![image](https://user-images.githubusercontent.com/31340618/57476963-f9516500-7297-11e9-8413-884b35ce88c6.png)

Attached, you'll find the svg file (change extension from zip to svg).
Am I missing something here?

Thanks!!

[ruler_draft_top_to_eagle.zip](https://github.com/gfwilliams/svgtoeagle/files/3163473/ruler_draft_top_to_eagle.zip)

**Comment by ghost** [comment]
Update:
I needed to ungroup the mm and inches scales one by one (select all -> ungroup didn't work).
Only thing which is missind are mm and inches scales now (they show up in the svgtoeagle preview!).
Also all inner "circles" are filled (Like a 0, 8, 9, 4, etc)
Current status:
![image](https://user-images.githubusercontent.com/31340618/57480063-13427600-729f-11e9-99ed-e34099f1dda5.png)

**Comment by ghost** [comment]
For comparison, this is the first "0" of the top scale (filled):
polygon 0.1mm (1.779104mm 30.891163mm) (1.779104mm 25.899166mm);
polygon 0.1mm (3.929528mm 27.075838mm) (3.861026mm 27.061928mm) (3.804823mm 27.020361mm) (3.765977mm 26.961881mm) (3.740311mm 26.896381mm) (3.723158mm 26.828104mm) (3.711421mm 26.758674mm) (3.703448mm 26.688706mm) (3.695169mm 26.548125mm) (3.693772mm 26.407285mm) (3.698407mm 26.266520mm) (3.703769mm 26.196305mm) (3.711932mm 26.126359mm) (3.723928mm 26.056973mm) (3.741466mm 25.988803mm) (3.767713mm 25.923540mm) (3.807418mm 25.865662mm) (3.864542mm 25.825387mm) (3.933357mm 25.813027mm) (4.001584mm 25.828240mm) (4.057182mm 25.870636mm) (4.095508mm 25.929461mm) (4.120765mm 25.995122mm) (4.137679mm 26.063454mm) (4.149244mm 26.132915mm) (4.157114mm 26.202894mm) (4.162249mm 26.273131mm) (4.165199mm 26.343497mm) (4.166467mm 26.484337mm) (4.161646mm 26.625090mm) (4.156193mm 26.695306mm) (4.147895mm 26.765230mm) (4.135741mm 26.834584mm) (4.117945mm 26.902700mm) (4.091261mm 26.967770mm) (4.050787mm 27.025109mm) (3.992936mm 27.064318mm) (3.929528mm 27.075838mm);

This is another "0" (not filled), made with another font, part of one of the "DNA" things:
polygon 0.1mm (181.666987mm 6.568434mm) (181.668005mm 6.215678mm) (181.675288mm 6.074785mm) (181.682038mm 6.004557mm) (181.691001mm 5.934580mm) (181.702482mm 5.864979mm) (181.716693mm 5.795871mm) (181.733844mm 5.727443mm) (181.754223mm 5.659908mm) (181.778059mm 5.593516mm) (181.805658mm 5.528585mm) (181.837164mm 5.465487mm) (181.872885mm 5.404649mm) (181.912822mm 5.346523mm) (181.957070mm 5.291596mm) (182.005581mm 5.240392mm) (182.058049mm 5.193282mm) (182.114537mm 5.151024mm) (182.174579mm 5.114076mm) (182.237866mm 5.082930mm) (182.303802mm 5.057910mm) (182.371725mm 5.038941mm) (182.441068mm 5.026032mm) (182.511219mm 5.018668mm) (182.581708mm 5.016591mm) (182.652182mm 5.019443mm) (182.722252mm 5.027518mm) (182.791402mm 5.041395mm) (182.859098mm 5.061162mm) (182.924646mm 5.087151mm) (182.987498mm 5.119158mm) (183.047071mm 5.156892mm) (183.102914mm 5.199967mm) (183.154881mm 5.247649mm) (183.202730mm 5.299465mm) (183.246348mm 5.354888mm) (183.285687mm 5.413434mm) (183.320746mm 5.474638mm) (183.351687mm 5.538038mm) (183.378688mm 5.603205mm) (183.402007mm 5.669781mm) (183.421903mm 5.737467mm) (183.438617mm 5.806003mm) (183.452392mm 5.875185mm) (183.463502mm 5.944851mm) (183.472093mm 6.014873mm) (183.478537mm 6.085130mm) (183.485271mm 6.226056mm) (183.485804mm 6.649360mm) (183.481153mm 6.790372mm) (183.468864mm 6.930922mm) (183.459497mm 7.000847mm) (183.447612mm 7.070384mm) (183.433013mm 7.139404mm) (183.415524mm 7.207746mm) (183.394837mm 7.275184mm) (183.370678mm 7.341469mm) (183.342822mm 7.406271mm) (183.310944mm 7.469197mm) (183.274932mm 7.529842mm) (183.234559mm 7.587687mm) (183.189827mm 7.642226mm) (183.140864mm 7.692988mm) (183.087798mm 7.739432mm) (183.030906mm 7.781106mm) (182.970364mm 7.817280mm) (182.906689mm 7.847620mm) (182.840494mm 7.871908mm) (182.772330mm 7.889982mm) (182.702874mm 7.902245mm) (182.632658mm 7.908812mm) (182.574617mm 7.910008mm) (182.588944mm 7.595120mm) (182.646675mm 7.590001mm) (182.714517mm 7.571032mm) (182.777837mm 7.540123mm) (182.835311mm 7.499320mm) (182.886616mm 7.450959mm) (182.930508mm 7.395794mm) (182.966811mm 7.335355mm) (182.996493mm 7.271383mm) (183.020490mm 7.205055mm) (183.039691mm 7.137186mm) (183.054855mm 7.068285mm) (183.066627mm 6.998737mm) (183.075558mm 6.928758mm) (183.081936mm 6.858500mm) (183.086151mm 6.788069mm) (183.089123mm 6.647015mm) (183.088719mm 6.223698mm) (183.082921mm 6.082730mm) (183.077011mm 6.012428mm) (183.068694mm 5.942374mm) (183.057503mm 5.872730mm) (183.043050mm 5.803677mm) (183.024753mm 5.735561mm) (183.001773mm 5.668867mm) (182.973351mm 5.604323mm) (182.938421mm 5.543067mm) (182.896143mm 5.486663mm) (182.846227mm 5.436892mm) (182.789981mm 5.394388mm) (182.727775mm 5.361295mm) (182.660693mm 5.339795mm) (182.590800mm 5.331010mm) (182.520536mm 5.335521mm) (182.452776mm 5.354738mm) (182.389973mm 5.386669mm) (182.333096mm 5.428313mm) (182.282034mm 5.476921mm) (182.237398mm 5.531504mm) (182.199432mm 5.590920mm) (182.167716mm 5.653913mm) (182.141554mm 5.719413mm) (182.120303mm 5.786677mm) (182.103298mm 5.855138mm) (182.089943mm 5.924406mm) (182.079801mm 5.994212mm) (182.072421mm 6.064373mm) (182.067463mm 6.134750mm) (182.064734mm 6.205246mm) (182.064250mm 6.699111mm) (182.069805mm 6.840091mm) (182.075619mm 6.910391mm) (182.083806mm 6.980467mm) (182.094787mm 7.050143mm) (182.109063mm 7.119228mm) (182.127101mm 7.187421mm) (182.149774mm 7.254213mm) (182.177873mm 7.318905mm) (182.212351mm 7.380410mm) (182.254193mm 7.437147mm) (182.303689mm 7.487338mm) (182.359581mm 7.530294mm) (182.421447mm 7.564023mm) (182.488287mm 7.586244mm) (182.558083mm 7.595782mm) (182.563996mm 7.595924mm) (182.549635mm 7.909653mm) (182.491678mm 7.906809mm) (182.421705mm 7.897907mm) (182.352701mm 7.883361mm) (182.285263mm 7.862703mm) (182.219990mm 7.835980mm) (182.157574mm 7.803198mm) (182.098485mm 7.764699mm) (182.043095mm 7.721045mm) (181.991693mm 7.672760mm) (181.944425mm 7.620393mm) (181.901469mm 7.564453mm) (181.862905mm 7.505403mm) (181.828589mm 7.443768mm) (181.798407mm 7.380023mm) (181.772052mm 7.314587mm) (181.749330mm 7.247796mm) (181.730000mm 7.179960mm) (181.713722mm 7.111315mm) (181.700286mm 7.042059mm) (181.689499mm 6.972338mm) (181.674658mm 6.832036mm) (181.670346mm 6.761627mm) (181.666987mm 6.620573mm) (181.666987mm 6.568434mm);

**Comment by gfwilliams** [comment]
It looks to me like the problem is because the `0` you have has a `.` in the middle of it.

That's a polygon inside a hole inside a polygon, which the tool isn't used to handling. I just tried taking it out and it looks like it's fine now.

If you really want that dot then you could either put it back manually, or you could break the path apart into its 3 parts, then recombine just the outer 2 - so you then have two shapes - the outer `0` and the inner `.`

**Comment by gfwilliams** [comment]
Also, about your scales - you have defined those as simple strokes, not filled rectangles - so that might be affecting how they're getting rendered (if there's a small line width, which you'd probably want for your filled areas). In inkscape you can highlight them and do `stroke to path` which will bring them into eagle as filled polys.

**Comment by ghost** [comment]
Thanks for clarifying!
I will try those fixes and report back!
Very awesome tool, I use it a lot :)

**Comment by ghost** [comment]
Alright, so the scale lines do work!
Filled spaces in the numbers (of the ruler) still appear filled (0's, 4's, 6's, 8's, etc).
I compared the objects to the "0" of the "DNA250", they seem the same.
Nevertheless, the numbers on the scale are filled, on the "250" they're not.
Here's the current SVG file (rename to .svg instead of .zip):

[ruler_draft_top_to_eagle2.zip](https://github.com/gfwilliams/svgtoeagle/files/3188583/ruler_draft_top_to_eagle2.zip)

update: It is working with another font, so I redid all the numbers.
So far so good, but I did have similar issues with another vector (no letters or numbers) which did contain some forms only
