### ISSUE TITLE
Allow creation of 'line' rather than 'polygon' for outline layer

### ISSUE THREAD

**Issue by EmbeddedMan** [gfwilliams/svgtoeagle#14]
Using a polygon in the outline layer can confuse Eagle (and a board house's gerber importer).

Instead, it would be really awesome if a choice could be given to either generate a polygon (for layers like silk or copper) or a line (for the outline/Dimension layer). In addition, it's nice to be able to default to a zero width line for the outline/Dimension layer.

Currently I use your tool, but then hand modify the output to switch "polygon" to "line" and remove the signal name (since lines don't get signal names). This works splendidly for board outlines. But it would make the tool easier to use if these were just options when creating the output.

Thanks SO MUCH for this tool - I could not create cool boards without this tool!

**Comment by joymonkey** [comment]
@EmbeddedMan , thanks for the tip . I've been having trouble with my dimension layer and manually editing it as you say works great!

**Comment by gfwilliams** [comment]
Any news on the fix for this?

**Comment by EmbeddedMan** [comment]
My apologies. I have gotten distracted by other activities. I will try to
create PRs for all of these issues in the next day or two.

**Comment by gfwilliams** [comment]
Great - thanks!

**Comment by mirzafahad** [comment]
Been looking for a way to draw an outline. @EmbeddedMan 's workaround worked great! Thanks!

**Comment by gfwilliams** [comment]
Thanks! Just looked into this more and realised this was what happened: https://github.com/gfwilliams/svgtoeagle/issues/17#issuecomment-625085971

It always used to work (automatically changing "polygon" to "line" for non-filled shapes) but someone contributed some changes that broke it. I asked them about it back in May to see if there was a reason, but they could never be bothered to respond so I never put the fix in.

I've just added a fix, so in future this should all work fine.
