### ISSUE TITLE
Warn user if any SVG objects do not have a fill or stroke defined

### ISSUE THREAD

**Issue by EmbeddedMan** [gfwilliams/svgtoeagle#18]
This currently causes silent failure to output those objects in the .scr.

**Comment by gfwilliams** [comment]
There are usually some that don't have a fill or stroke that are never meant to be rendered, hence why they are left out rather than converted in the first place.

I think you get a warning if there are *no* objects?

**Comment by Spider84** [comment]
my svg exported from CorelDRAW use **class** as style of fill and stroke. Script don't work with this files :(

**Comment by gfwilliams** [comment]
Please could you post up a (simple) example file?
