### ISSUE TITLE
Clear result area on start of new conversion

### ISSUE THREAD

**Issue by EmbeddedMan** [gfwilliams/svgtoeagle#19]
Because it is common (at least for me) to convert the same svg file many times, and because some conversions may take minutes or more, it would be a good idea to clear the result area of the page when the Convert button is clicked so that the user knows (or can guess) that the conversion has started and is in progress.

**Comment by gfwilliams** [comment]
Feel free to contribute this as a fix if you want.

**Comment by EmbeddedMan** [comment]
You bet! I'm preparing fixes for all of these recently submitted issues.

**Comment by gfwilliams** [comment]
Awesome, thank you!

**Comment by gfwilliams** [comment]
Any news on the fix for this?
