### ISSUE TITLE
file generates errors, parts missing

### ISSUE THREAD

**Issue by mxa** [gfwilliams/svgtoeagle#2]
Hi, thanks for this great tool! It works so much better than any other method I tried so far. But i have issues with this file.

**Comment by gfwilliams** [comment]
Can you try again? This seems to work fine for me:

![image](https://user-images.githubusercontent.com/754445/38413902-e81ca1e8-3984-11e8-9271-48e4c08480dd.png)

**Comment by mxa** [comment]
The errors resulted from trying to import it into a copper layer where eagle was trying to do some extra steps.

**Comment by gfwilliams** [comment]
the recent changes I made would have helped with that a lot
