### ISSUE TITLE
Top/Bottom Copper Layer Issues

### ISSUE THREAD

**Issue by twinkletwinkie** [gfwilliams/svgtoeagle#3]
This works great when bringing it into a Silk Screen layer but I would like to use it for copper layer objects as well.  As is whenever I import the script into the top layer I get a basic out line of the objects but you cannot apply Ratsnests to them because Eagle CAD gives an invalid polygon error message.

![polygon_error](https://user-images.githubusercontent.com/5308062/38349100-747c9a02-3873-11e8-8a9b-cbabf175ef6f.PNG)

![image](https://user-images.githubusercontent.com/5308062/38349140-a6532c12-3873-11e8-88b0-a25c0d57e1eb.png)

Any help at all with this would be greatly appreciated!

**Comment by gfwilliams** [comment]
Do you have any idea what it is about the polygon that Eagle thinks is invalid? Perhaps you could strip your file down to just a single shape that has problems and then try tweaking it manually in eagle to see why it doesn't like it?

**Comment by twinkletwinkie** [comment]
I believe it’s because the polygons are overlapping.  It doesn’t care when
it’s the Silk Screen but it’s against what it would allow in the Copper
layer.  I’ll try a less complex shape and attempt to recreate the issue.

**Comment by twinkletwinkie** [comment]
Here you go.  

SVG:
https://pastebin.com/29esWfmC

Output:
`change layer Top; change rank 3; ch pour solid; SET WIRE_BEND 2;
polygon 0.1mm  (9.845400mm 5.784934mm) (9.951178mm 5.787450mm) (10.056836mm 5.792976mm) (10.162285mm 5.801648mm) (10.267414mm 5.813590mm) (10.372093mm 5.828977mm) (10.476192mm 5.847882mm) (10.630927mm 5.883116mm) (10.732897mm 5.911336mm) (10.833714mm 5.943432mm) (10.982375mm 5.998940mm) (11.127394mm 6.063377mm) (11.268127mm 6.136693mm) (11.313890mm 6.163239mm) (11.403619mm 6.219291mm) (11.490979mm 6.278977mm) (11.575789mm 6.342228mm) (11.657857mm 6.408999mm) (11.697783mm 6.443712mm) (11.775390mm 6.515619mm) (11.813004mm 6.552818mm) (11.885810mm 6.629585mm) (11.955283mm 6.709381mm) (12.053016mm 6.834402mm) (12.142859mm 6.965208mm) (12.198331mm 7.055303mm) (12.250317mm 7.147452mm) (12.322372mm 7.288848mm) (12.386477mm 7.434014mm) (12.442416mm 7.582523mm) (12.490263mm 7.733834mm) (12.530215mm 7.887414mm) (12.562529mm 8.042790mm) (12.587547mm 8.199504mm) (12.605614mm 8.357173mm) (12.617105mm 8.515460mm) (12.621305mm 8.621183mm) (12.622871mm 8.726974mm) (12.622909mm 11.001880mm) (12.620302mm 11.160563mm) (12.611722mm 11.319036mm) (12.596748mm 11.477029mm) (12.575002mm 11.634230mm) (12.546118mm 11.790280mm) (12.509733mm 11.944749mm) (12.465570mm 12.097178mm) (12.431701mm 12.197410mm) (12.374097mm 12.345282mm) (12.331151mm 12.441973mm) (12.260043mm 12.583845mm) (12.181732mm 12.721869mm) (12.095462mm 12.855057mm) (12.033497mm 12.940812mm) (11.968006mm 13.023910mm) (11.899014mm 13.104117mm) (11.863234mm 13.143089mm) (11.789189mm 13.218657mm) (11.711892mm 13.290900mm) (11.672092mm 13.325753mm) (11.590254mm 13.392807mm) (11.548263mm 13.424984mm) (11.462278mm 13.486636mm) (11.328635mm 13.572201mm) (11.190311mm 13.649982mm) (11.047523mm 13.719216mm) (10.950065mm 13.760392mm) (10.851024mm 13.797603mm) (10.699876mm 13.845949mm) (10.546206mm 13.885550mm) (10.390596mm 13.916689mm) (10.286043mm 13.932910mm) (10.128352mm 13.950747mm) (9.969996mm 13.961204mm) (9.811335mm 13.964732mm) (9.652662mm 13.961639mm) (9.494277mm 13.951660mm) (9.336532mm 13.934291mm) (9.231928mm 13.918409mm) (9.076210mm 13.887819mm) (8.922395mm 13.848783mm) (8.771074mm 13.800986mm) (8.671878mm 13.764187mm) (8.526094mm 13.701505mm) (8.431200mm 13.654718mm) (8.292601mm 13.577433mm) (8.158586mm 13.492454mm) (8.115106mm 13.462316mm) (8.030132mm 13.399283mm) (7.947912mm 13.332701mm) (7.868619mm 13.262651mm) (7.792420mm 13.189254mm) (7.755535mm 13.151329mm) (7.684206mm 13.073188mm) (7.583592mm 12.950477mm) (7.490766mm 12.821771mm) (7.433258mm 12.732964mm) (7.353483mm 12.595779mm) (7.305004mm 12.501740mm) (7.239412mm 12.357240mm) (7.181949mm 12.209316mm) (7.148120mm 12.109068mm) (7.103986mm 11.956635mm) (7.067567mm 11.802170mm) (7.038543mm 11.646148mm) (7.016612mm 11.488971mm) (7.001382mm 11.331002mm) (6.992466mm 11.172549mm) (6.989500mm 11.013870mm) (6.989489mm 8.738969mm) (6.990758mm 8.633169mm) (6.994601mm 8.527431mm) (7.005445mm 8.369099mm) (7.022724mm 8.211341mm) (7.046814mm 8.054482mm) (7.078123mm 7.898900mm) (7.116918mm 7.745022mm) (7.163513mm 7.593319mm) (7.218094mm 7.444309mm) (7.280828mm 7.298541mm) (7.327157mm 7.203424mm) (7.351869mm 7.156645mm) (7.404048mm 7.064604mm) (7.459684mm 6.974614mm) (7.549593mm 6.843853mm) (7.613829mm 6.759782mm) (7.681490mm 6.678444mm) (7.716573mm 6.638847mm) (7.789198mm 6.561910mm) (7.904083mm 6.452444mm) (8.025693mm 6.350500mm) (8.153460mm 6.256385mm) (8.241755mm 6.198095mm) (8.332352mm 6.143452mm) (8.425390mm 6.093080mm) (8.472689mm 6.069381mm) (8.568682mm 6.024891mm) (8.666433mm 5.984413mm) (8.815894mm 5.931086mm) (8.917154mm 5.900419mm) (9.019510mm 5.873632mm) (9.174694mm 5.840442mm) (9.279030mm 5.822876mm) (9.383891mm 5.808790mm) (9.489150mm 5.798059mm) (9.594688mm 5.790558mm) (9.700402mm 5.786154mm) (9.806198mm 5.784717mm) (9.806198mm 6.892659mm) (9.819899mm 6.892699mm) (9.925650mm 6.895864mm) (9.978436mm 6.899422mm) (10.083622mm 6.910762mm) (10.187990mm 6.928053mm) (10.291107mm 6.951687mm) (10.392467mm 6.981978mm) (10.442315mm 6.999694mm) (10.539984mm 7.040337mm) (10.634449mm 7.087943mm) (10.725153mm 7.142382mm) (10.811587mm 7.203367mm) (10.893358mm 7.270482mm) (10.970189mm 7.343201mm) (11.042124mm 7.420776mm) (11.076303mm 7.461152mm) (11.109141mm 7.502630mm) (11.170629mm 7.588717mm) (11.226317mm 7.678661mm) (11.276025mm 7.772046mm) (11.298614mm 7.819883mm) (11.339267mm 7.917552mm) (11.357354mm 7.967271mm) (11.389144mm 8.068172mm) (11.402892mm 8.119260mm) (11.426279mm 8.222439mm) (11.435970mm 8.274446mm) (11.451571mm 8.379087mm) (11.462357mm 8.484338mm) (11.468678mm 8.589952mm) (11.470847mm 8.695730mm) (11.470728mm 11.076444mm) (11.467684mm 11.182199mm) (11.460443mm 11.287751mm) (11.448640mm 11.392893mm) (11.440931mm 11.445231mm) (11.421714mm 11.549271mm) (11.397161mm 11.652180mm) (11.367022mm 11.753591mm) (11.349774mm 11.803599mm) (11.310831mm 11.901962mm) (11.265868mm 11.997725mm) (11.214867mm 12.090408mm) (11.187123mm 12.135451mm) (11.157916mm 12.179562mm) (11.095211mm 12.264767mm) (11.061793mm 12.305777mm) (10.991180mm 12.384555mm) (10.915793mm 12.458772mm) (10.876213mm 12.493876mm) (10.793417mm 12.559719mm) (10.750272mm 12.590329mm) (10.660739mm 12.646668mm) (10.614473mm 12.672321mm) (10.567291mm 12.696245mm) (10.470477mm 12.738878mm) (10.420990mm 12.757583mm) (10.320233mm 12.789820mm) (10.269105mm 12.803401mm) (10.165679mm 12.825642mm) (10.113503mm 12.834391mm) (10.008508mm 12.847383mm) (9.902965mm 12.854706mm) (9.797185mm 12.856781mm) (9.691428mm 12.853846mm) (9.638638mm 12.850407mm) (9.533420mm 12.839356mm) (9.428997mm 12.822372mm) (9.325796mm 12.799114mm) (9.224302mm 12.769267mm) (9.174367mm 12.751801mm) (9.076473mm 12.711712mm) (8.981690mm 12.664735mm) (8.890566mm 12.611003mm) (8.803596mm 12.550776mm) (8.721165mm 12.484477mm) (8.681742mm 12.449200mm) (8.606607mm 12.374725mm) (8.536910mm 12.295143mm) (8.472656mm 12.211101mm) (8.414083mm 12.123008mm) (8.361405mm 12.031266mm) (8.337319mm 11.984168mm) (8.293670mm 11.887799mm) (8.274096mm 11.838651mm) (8.239374mm 11.738717mm) (8.210393mm 11.636971mm) (8.186937mm 11.533804mm) (8.177178mm 11.481809mm) (8.161444mm 11.377184mm) (8.150468mm 11.271954mm) (8.143968mm 11.166356mm) (8.141580mm 11.060577mm) (8.141528mm 8.732772mm) (8.142475mm 8.626968mm) (8.147258mm 8.521278mm) (8.156358mm 8.415866mm) (8.162609mm 8.363334mm) (8.178753mm 8.258778mm) (8.200007mm 8.155134mm) (8.226671mm 8.052758mm) (8.242106mm 8.002152mm) (8.277324mm 7.902396mm) (8.318478mm 7.804937mm) (8.365657mm 7.710245mm) (8.391506mm 7.664091mm) (8.447659mm 7.574429mm) (8.477915mm 7.531036mm) (8.509585mm 7.488662mm) (8.577022mm 7.407150mm) (8.649973mm 7.330544mm) (8.728000mm 7.259106mm) (8.810830mm 7.193311mm) (8.853959mm 7.162677mm) (8.943412mm 7.106204mm) (8.989623mm 7.080459mm) (9.036740mm 7.056409mm) (9.133413mm 7.013449mm) (9.182828mm 6.994558mm) (9.283457mm 6.961909mm) (9.334524mm 6.948111mm) (9.437847mm 6.925397mm) (9.489985mm 6.916406mm) (9.594918mm 6.902946mm) (9.700431mm 6.895158mm) (9.806198mm 6.892659mm) (9.806198mm 5.784717mm) (9.845400mm 5.784934mm);
`

Results as Top Cu Layer:
![image](https://user-images.githubusercontent.com/5308062/38365637-0de6ef1c-38ab-11e8-984b-c62b81871806.png)

Error when attempting to assign ratsnest:
![image](https://user-images.githubusercontent.com/5308062/38365669-2f2fc66c-38ab-11e8-9f95-031a2d4638fc.png)

Results with the same output but on a Silk Screen Layer:
![image](https://user-images.githubusercontent.com/5308062/38365750-7e6a38fc-38ab-11e8-8811-d832ce37fced.png)

**Comment by gfwilliams** [comment]
Perfect, thanks - it looks like the middle of the `O` is going in the wrong direction. I'll see how easy it is to change the code to fix it.

**Comment by gfwilliams** [comment]
Ok, try now - make sure you refresh the page
