### ISSUE TITLE
Copper Layer Issues Part 2

### ISSUE THREAD

**Issue by twinkletwinkie** [gfwilliams/svgtoeagle#4]
Hello again!  Thanks for the work you did on improving the script for copper layer usage but unfortunately it looks like we still have some bugs.

**Screenshots:**
After running Ratsnest
![image](https://user-images.githubusercontent.com/5308062/38437257-e60dcf60-39a4-11e8-857c-4cb3474fc6db.png)

Error When running Ratsnest
![image](https://user-images.githubusercontent.com/5308062/38437278-efb8ce52-39a4-11e8-8199-7b57580b8464.png)

**Results in the Silk Screen Layer:**
![image](https://user-images.githubusercontent.com/5308062/38437397-5249166c-39a5-11e8-9fd0-57f4d67618f7.png)

**SVG:**
https://pastebin.com/Ze8G9i98

**Generated Script:**
https://pastebin.com/Yu8KqsyW

Thanks again for your help!

**Comment by gfwilliams** [comment]
Thanks - but this is just a little utility I made. I can't afford to spend hours working on it - especially if it's just on a test file that's been made to stress-test it, and on the copper layer too.

If you hit problems like this, you can just manually fix up the small areas that have issues by moving/deleting the lines in Eagle.

Of course if you (or anyone else) actually feels like fixing this in the code then a PR is more than welcome :)
