### ISSUE TITLE
Wrong placement in eagle

### ISSUE THREAD

**Issue by ghost** [gfwilliams/svgtoeagle#8]
Hi,

I followed the youtube tutorial but after pasting the code in eagle, the polygons are not in the location as I placed it in inkscape. 
The placement preview on the generator page looks correct.
All units are set to mm.
Is that a known issue?

Thanks

**Comment by gfwilliams** [comment]
I just tried it again here and it works fine for me.

Could you post up your svg file along with a screenshot of what happens in eagle vs what you're expecting?

**Comment by ghost** [comment]
I was able to move the imported polygons by hand, so it's a minor issue.
SVG:
https://www.file-upload.net/download-13473047/spwm_pot_led.svg.html
Screenshot (marked red was imported):
https://s15.directupload.net/images/190117/oabbfmw2.png

Also, for some reason, this feature totally wrecks my eagle client and makes the window infinitely wide.

**Comment by gfwilliams** [comment]
Ahh - thanks. That's interesting...

Looks like your zero coordinate marker is top left - usually it's bottom left (which is the same as Inkscape which makes it nice and easy). In the Eagle versions I've used thus far, all but the super pro versions refuse to put anything *below* the coordinate marker so most people arrange their boards with 0,0 in the bottom left.

Maybe it's different in newer versions (it was a weird restriction).

But `svgtoeagle` doesn't know how your board is set up in eagle, so all I can suggest is to move the whole board so 0,0 is in the bottom left then you'll be sorted.

**Comment by ghost** [comment]
Ah, that makes sense!
I actually created the pcb in Fusion and payed no attention to where the origin is.
Thanks for pointing that out!
